name: whisperx-web-ui
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python=3.10
  - conda-forge::ffmpeg
  - conda-forge::numpy=1.24.4
  - pip
  - pip:
    - gradio==5.9.1
    - whisperx==3.3.0
    - torch==2.2.0
    - torchaudio==2.2.0
