name: whisperx-web-ui
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python=3.10
  - pip
  - numpy=1.24.4
  - ffmpeg
  - pytorch=2.2.0
  - torchaudio=2.2.0
  - pip:
      - aiofiles==23.2.1
      - aiohappyeyeballs==2.4.4
      - aiohttp==3.11.11
      - aiosignal==1.3.2
      - alembic==1.14.0
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.8.0
      - asteroid-filterbanks==0.4.0
      - attrs==24.3.0
      - audioread==3.0.1
      - av==14.0.1
      - certifi==2024.12.14
      - cffi==1.17.1
      - charset-normalizer==3.4.1
      - click==8.1.8
      - colorama==0.4.6
      - coloredlogs==15.0.1
      - colorlog==6.9.0
      - contourpy==1.3.1
      - ctranslate2==4.4.0
      - cycler==0.12.1
      - decorator==5.1.1
      - docopt==0.6.2
      - einops==0.8.0
      - fastapi==0.115.6
      - faster-whisper==1.1.0
      - ffmpy==0.5.0
      - filelock==3.16.1
      - flatbuffers==24.12.23
      - fonttools==4.55.3
      - frozenlist==1.5.0
      - fsspec==2024.12.0
      - gradio==5.9.1
      - gradio_client==1.5.2
      - greenlet==3.1.1
      - h11==0.14.0
      - httpcore==1.0.7
      - httpx==0.28.1
      - huggingface-hub==0.27.1
      - humanfriendly==10.0
      - HyperPyYAML==1.2.2
      - idna==3.10
      - Jinja2==3.1.5
      - joblib==1.4.2
      - julius==0.2.7
      - kiwisolver==1.4.8
      - lazy_loader==0.4
      - librosa==0.10.2.post1
      - llvmlite==0.43.0
      - Mako==1.3.8
      - markdown-it-py==3.0.0
      - MarkupSafe==2.1.5
      - matplotlib==3.10.0
      - mdurl==0.1.2
      - mpmath==1.3.0
      - msgpack==1.1.0
      - multidict==6.1.0
      - networkx==3.4.2
      - nltk==3.9.1
      - numba==0.60.0
      - onnxruntime==1.20.1
      - optuna==4.1.0
      - orjson==3.10.14
      - packaging==24.2
      - pandas==2.2.3
      - pillow==11.1.0
      - platformdirs==4.3.6
      - pooch==1.8.2
      - primePy==1.3
      - propcache==0.2.1
      - protobuf==5.29.3
      - pyannote.audio==3.3.2
      - pyannote.core==5.0.0
      - pyannote.database==5.1.0
      - pyannote.metrics==3.2.1
      - pyannote.pipeline==3.0.1
      - pycparser==2.22
      - pydantic==2.10.5
      - pydantic_core==2.27.2
      - pydub==0.25.1
      - Pygments==2.19.1
      - pyparsing==3.2.1
      - pyreadline3==3.5.4
      - python-dateutil==2.9.0.post0
      - python-multipart==0.0.20
      - pytz==2024.2
      - PyYAML==6.0.2
      - regex==2024.11.6
      - requests==2.32.3
      - rich==13.9.4
      - ruamel.yaml==0.18.10
      - ruamel.yaml.clib==0.2.12
      - ruff==0.9.0
      - safehttpx==0.1.6
      - safetensors==0.5.2
      - scikit-learn==1.6.0
      - scipy==1.15.0
      - semantic-version==2.10.0
      - semver==3.0.2
      - sentencepiece==0.2.0
      - shellingham==1.5.4
      - six==1.17.0
      - sniffio==1.3.1
      - sortedcontainers==2.4.0
      - soundfile==0.13.0
      - soxr==0.5.0.post1
      - speechbrain==1.0.2
      - SQLAlchemy==2.0.36
      - starlette==0.41.3
      - sympy==1.13.1
      - tabulate==0.9.0
      - tensorboardX==2.6.2.2
      - threadpoolctl==3.5.0
      - tokenizers==0.21.0
      - tomlkit==0.13.2
      - torch-audiomentations==0.11.2
      - torch_pitch_shift==1.2.5
      - torchmetrics==1.6.1
      - tqdm==4.67.1
      - transformers==4.47.1
      - typer==0.15.1
      - typing_extensions==4.12.2
      - tzdata==2024.2
      - urllib3==2.3.0
      - uvicorn==0.34.0
      - websockets==14.1
      - whisperx==3.3.0
      - yarl==1.18.3
