name: whisperx-env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - conda-forge::ffmpeg
  - conda-forge::numpy=1.24.4
  - pip
  - pip:
    - gradio
    - whisperx
    - torch==2.1.0
    - torchvision==0.16.0
    - torchaudio==2.1.0
